name: first_workflow
"on": Workflow_dispatch
jobs:
  first_job:
    runs_on: ubuntu-latest
    steps:
      - name: Print greetings
        run: echo "Hello world"
      - name: Print good bye
        run: echo "Done - bye"
